# Generated by Django 6.0.2 on 2026-02-25 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory_items',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='inventory_items',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
